### ISSUE TITLE
Rails 5 Support

### ISSUE THREAD

**Issue by plicjo** [rwz/adequate_exposure#24]
I'd like to add support for Rails 5.

How would you want me to go about doing this, without breaking the Rails 4 stuff?

Here's what I did a while back to get adequate_exposure running in Rails 5: https://github.com/plicjo/adequate_exposure/commit/e1a1b709b8599dd0f687ce37bd89247c21a76be5

I think the above is decent, but not adequate.

**Comment by rwz** [comment]
Would probably need to setup Appraisals and run CI for 4.x and 5.x separately or something

**Comment by plicjo** [comment]
You got it https://github.com/rwz/adequate_exposure/pull/25
